-- Inverse de 0022 : déclencheurs, politiques, fonctions et défauts ajoutés ; les reprises de données ne sont pas défaites.
DROP TRIGGER IF EXISTS incidents_org_fill ON incidents;
DROP TRIGGER IF EXISTS conversations_org_fill ON conversations;
DROP TRIGGER IF EXISTS notifications_org_fill ON notifications;
DROP TRIGGER IF EXISTS credits_org_fill ON credits;
DROP TRIGGER IF EXISTS weekly_statements_org_fill ON weekly_statements;
DROP TRIGGER IF EXISTS vehicles_org_fill ON vehicles;
DROP TRIGGER IF EXISTS quotes_org_fill ON quotes;
DROP FUNCTION IF EXISTS org_fill_from_ride();
DROP FUNCTION IF EXISTS org_fill_from_user();
DROP FUNCTION IF EXISTS org_fill_conversation();
DROP FUNCTION IF EXISTS org_fill_notification();
DROP FUNCTION IF EXISTS org_fill_from_driver();
DROP FUNCTION IF EXISTS org_fill_from_client();
DROP POLICY IF EXISTS org_insert ON organizations;
DROP POLICY IF EXISTS org_read ON consents;
DROP POLICY IF EXISTS org_isolation ON devices;
DROP POLICY IF EXISTS org_isolation ON compliance_checks;
DROP FUNCTION IF EXISTS app_scope_allows_user(uuid);
ALTER FUNCTION next_counter(text) SECURITY INVOKER RESET search_path;
ALTER FUNCTION ensure_driver_locations_partition(date) SECURITY INVOKER RESET search_path;
ALTER TABLE clients ALTER COLUMN organization_id DROP DEFAULT;
ALTER TABLE drivers ALTER COLUMN organization_id DROP DEFAULT;
ALTER TABLE vehicles ALTER COLUMN organization_id DROP DEFAULT;
ALTER TABLE quotes ALTER COLUMN organization_id DROP DEFAULT;
ALTER TABLE rides ALTER COLUMN organization_id DROP DEFAULT;
ALTER TABLE credits ALTER COLUMN organization_id DROP DEFAULT;
ALTER TABLE weekly_statements ALTER COLUMN organization_id DROP DEFAULT;
ALTER TABLE incidents ALTER COLUMN organization_id DROP DEFAULT;
ALTER TABLE conversations ALTER COLUMN organization_id DROP DEFAULT;
ALTER TABLE notifications ALTER COLUMN organization_id DROP DEFAULT;
ALTER TABLE leads ALTER COLUMN organization_id DROP DEFAULT;
DROP FUNCTION IF EXISTS app_scope_organization_id();
