/** Point d'entrée de bibliothèque : le worker et les tests réutilisent la configuration, le journal et les modules d'infrastructure. */
export { createApp } from './bootstrap.js';
export { AppModule } from './app.module.js';
export { CoreModule } from './core.module.js';
export { APP_ENV, envSchema, loadDotenvFromRoot, loadEnv, type AppEnv } from './config/env.js';
export { APP_LOGGER, createLogger, currentCorrelationId, PinoNestLogger } from './common/logger.js';
export { AppError } from './common/app-error.js';
export { DB, DbModule, type Database } from './infra/db.module.js';
export { REDIS, RedisModule } from './infra/redis.module.js';
export { QUEUE_NAMES, QueueModule, QueueService, type QueueName, type QueueStats } from './infra/queue.module.js';
export { AdaptersModule } from './adapters/adapters.module.js';
export * from './adapters/types.js';
export * from './adapters/mock/index.js';
export { SettingsModule, SettingsService } from './common/settings.service.js';
export { RateLimitService } from './common/rate-limit.service.js';
export { AuthModule } from './modules/auth/auth.module.js';
export { TokensService } from './modules/auth/tokens.service.js';
export { StaffAuthService } from './modules/auth/staff-auth.service.js';
export { listRoutePolicies, assertRoutePolicies, type RoutePolicy } from './modules/auth/route-policies.js';
export * from './modules/auth/actor.js';
export { UsersModule } from './modules/users/users.module.js';
export { UsersService } from './modules/users/users.service.js';
export { AuditModule } from './modules/audit/audit.module.js';
export { AuditService, maskSensitive } from './modules/audit/audit.service.js';
export { PrivacyModule } from './modules/privacy/privacy.module.js';
export { PrivacyJobsService, anonymizedPhone } from './modules/privacy/privacy-jobs.service.js';
export { DomainEventsModule, DomainEventsService, type DomainEvents } from './common/domain-events.js';
export { PricingModule } from './modules/pricing/pricing.module.js';
export { RidesModule } from './modules/rides/rides.module.js';
export { PaymentsModule } from './modules/payments/payments.module.js';
export { PaymentsService } from './modules/payments/payments.service.js';
export { PaymentJobsService } from './modules/payments/payment-jobs.service.js';
export { SettlementModule } from './modules/settlement/settlement.module.js';
export { SettlementJobsService } from './modules/settlement/settlement-jobs.service.js';
export { NotificationsModule } from './modules/notifications/notifications.module.js';
export { ComplianceModule } from './modules/compliance/compliance.module.js';
export { ComplianceJobsService } from './modules/compliance/compliance-jobs.service.js';
export { RetentionModule } from './modules/retention/retention.module.js';
export { RetentionJobsService } from './modules/retention/retention-jobs.service.js';
export { NotificationJobsService } from './modules/notifications/notification-jobs.service.js';
export { RidesService } from './modules/rides/rides.service.js';
export { PresenceService } from './modules/rides/presence.service.js';
export { ScheduledService } from './modules/rides/scheduled.service.js';
export { StuckRidesService } from './modules/rides/stuck-rides.service.js';
export { PackLifecycleService } from './modules/rides/pack-lifecycle.service.js';
export { DispatchService } from './modules/rides/dispatch.service.js';
export { LedgersModule } from './modules/ledgers/ledgers.module.js';
export { LedgerJobsService } from './modules/ledgers/ledger-jobs.service.js';
export { InvoicingModule } from './modules/invoicing/invoicing.module.js';
export { InvoicingService } from './modules/invoicing/invoicing.service.js';
export { SevService } from './modules/invoicing/sev.service.js';
export { InvoiceJobsService } from './modules/invoicing/invoice-jobs.service.js';
